-- Create announcements table
CREATE TABLE IF NOT EXISTS public.announcements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version_code INTEGER NOT NULL UNIQUE,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;

-- Allow read access to all users (public)
DROP POLICY IF EXISTS "Allow read access to all users" ON public.announcements;
CREATE POLICY "Allow read access to all users" ON public.announcements
  FOR SELECT TO public USING (true);
