-- Create announcement_views tracking table
CREATE TABLE IF NOT EXISTS public.announcement_views (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  announcement_id BIGINT REFERENCES public.announcements(id) ON DELETE CASCADE NOT NULL,
  seen_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, announcement_id)
);

-- Enable Row Level Security
ALTER TABLE public.announcement_views ENABLE ROW LEVEL SECURITY;

-- Allow users to view their own announcement views
DROP POLICY IF EXISTS "Users can view their own announcement views" ON public.announcement_views;
CREATE POLICY "Users can view their own announcement views" ON public.announcement_views
  FOR SELECT USING (auth.uid() = user_id);

-- Allow users to insert their own announcement views
DROP POLICY IF EXISTS "Users can insert their own announcement views" ON public.announcement_views;
CREATE POLICY "Users can insert their own announcement views" ON public.announcement_views
  FOR INSERT WITH CHECK (auth.uid() = user_id);
