-- Clear old milestones
TRUNCATE TABLE public.unlocked_milestones CASCADE;
TRUNCATE TABLE public.milestones CASCADE;

-- Insert 100 milestone definitions
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Aller Anfang...', 'Verbindet euch erfolgreich als Partner.', '🤝', 'days_connected', 1);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Zarte Keime', 'Seid seit 3 Tagen miteinander gekoppelt.', '🌱', 'days_connected', 3);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Erste Knospen', 'Seid seit einer Woche miteinander gekoppelt.', '🎋', 'days_connected', 7);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Gemeinsame Schritte', 'Seid seit 10 Tagen miteinander gekoppelt.', '🐾', 'days_connected', 10);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Zwei Wochen Vertrautheit', 'Seid seit 14 Tagen miteinander gekoppelt.', '🌿', 'days_connected', 14);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Glücksgefühle', 'Seid seit 21 Tagen miteinander gekoppelt.', '🍀', 'days_connected', 21);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Erster Monat', 'Seid seit einem vollen Monat gekoppelt.', '💖', 'days_connected', 30);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Leichtigkeit', 'Seid seit 45 Tagen miteinander gekoppelt.', '🪁', 'days_connected', 45);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Zwei Monde', 'Seid seit 60 Tagen miteinander gekoppelt.', '🌓', 'days_connected', 60);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Gemeinsame Blüte', 'Seid seit 75 Tagen miteinander gekoppelt.', '🌻', 'days_connected', 75);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Ein Vierteljahr', 'Seid seit 90 Tagen (3 Monaten) gekoppelt.', '🌅', 'days_connected', 90);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Schmetterlinge im Bauch', 'Seid seit 105 Tagen gekoppelt.', '🦋', 'days_connected', 105);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Gereifte Liebe', 'Seid seit 120 Tagen (4 Monaten) gekoppelt.', '🍇', 'days_connected', 120);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Amors Erben', 'Seid seit 135 Tagen gekoppelt.', '🏹', 'days_connected', 135);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Süße Zeiten', 'Seid seit 150 Tagen (5 Monaten) gekoppelt.', '🍉', 'days_connected', 150);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Honigmond-Gefühl', 'Seid seit 165 Tagen gekoppelt.', '🍯', 'days_connected', 165);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Halbes Jahr!', 'Ein halbes Jahr (180 Tage) voller geteilter Momente.', '🎉', 'days_connected', 180);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Unerschütterlich', 'Seid seit 200 Tagen miteinander gekoppelt.', '🌋', 'days_connected', 200);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Sternenkonstellation', 'Seid seit 220 Tagen miteinander gekoppelt.', '🌌', 'days_connected', 220);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Kirschen der Liebe', 'Seid seit 240 Tagen (8 Monaten) gekoppelt.', '🍒', 'days_connected', 240);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Im gleichen Boot', 'Seid seit 260 Tagen miteinander gekoppelt.', '🛶', 'days_connected', 260);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Fruchtbare Beziehug', 'Seid seit 280 Tagen miteinander gekoppelt.', '🍎', 'days_connected', 280);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Großes Jubiläum', 'Seid seit 300 Tagen miteinander gekoppelt.', '🎇', 'days_connected', 300);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Zukunftsvisionen', 'Seid seit 330 Tagen miteinander gekoppelt.', '🔮', 'days_connected', 330);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Ein ganzes Jahr!', 'Ihr seid ein volles Jahr (365 Tage) gekoppelt. Herzlichen Glückwunsch!', '👑', 'days_connected', 365);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Gemeinsamer Zirkus', 'Seid seit 400 Tagen miteinander gekoppelt.', '🎪', 'days_connected', 400);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Sanfter Ritt', 'Seid seit 430 Tagen miteinander gekoppelt.', '🛹', 'days_connected', 430);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Gemeinsamer Flusslauf', 'Seid seit 460 Tagen gekoppelt.', '🛶', 'days_connected', 460);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Ein halbes Jahrtausend', 'Ihr seid seit unglaublichen 500 Tagen gekoppelt.', '💎', 'days_connected', 500);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Gemeinsames Kunstwerk', 'Seid seit 550 Tagen miteinander gekoppelt.', '🎨', 'days_connected', 550);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Abenteurer', 'Seid seit 600 Tagen miteinander gekoppelt.', '⛺', 'days_connected', 600);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Eigenes Universum', 'Seid seit 650 Tagen miteinander gekoppelt.', '🪐', 'days_connected', 650);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Sicherer Hafen', 'Seid seit 700 Tagen miteinander gekoppelt.', '⚓', 'days_connected', 700);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Zwei Jahre Bisou!', 'Ihr seid seit zwei vollen Jahren gekoppelt. Was für ein Meilenstein!', '💍', 'days_connected', 730);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Dreier-Funke', 'Beantwortet an 3 Tagen in Folge die täglichen Fragen.', '🔥', 'streak', 3);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Fünfer-Glanz', 'Haltet eine Antwort-Serie (Streak) von 5 Tagen.', '✨', 'streak', 5);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Wochen-Feuer', 'Haltet eine Antwort-Serie (Streak) von 7 Tagen.', '🌟', 'streak', 7);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Zehner-Blitz', 'Haltet eine Antwort-Serie (Streak) von 10 Tagen.', '⚡', 'streak', 10);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Zwei Wochen Feuerwerk', 'Haltet eine Antwort-Serie (Streak) von 14 Tagen.', '💥', 'streak', 14);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Magische Serie', 'Haltet eine Antwort-Serie (Streak) von 18 Tagen.', '💫', 'streak', 18);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Zielwasser', 'Haltet eine Antwort-Serie (Streak) von 21 Tagen.', '🏹', 'streak', 21);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Karussell der Liebe', 'Haltet eine Antwort-Serie (Streak) von 25 Tagen.', '🎡', 'streak', 25);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Ein Monat Dauerbrenner', 'Beantwortet an 30 aufeinanderfolgenden Tagen eure Fragen.', '🕯️', 'streak', 30);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Sommerbrise', 'Haltet eine Antwort-Serie (Streak) von 35 Tagen.', '🎐', 'streak', 35);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Perfekt verzahnt', 'Haltet eine Antwort-Serie (Streak) von 40 Tagen.', '🧩', 'streak', 40);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Leicht schwebend', 'Haltet eine Antwort-Serie (Streak) von 45 Tagen.', '🎈', 'streak', 45);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Liebesfestung', 'Haltet eine Antwort-Serie (Streak) von 50 Tagen.', '🏰', 'streak', 50);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Biwak im Sturm', 'Haltet eine Antwort-Serie (Streak) von 55 Tagen.', '⛺', 'streak', 55);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Heiße Lava', 'Haltet eine Antwort-Serie (Streak) von 60 Tagen (2 Monaten).', '🌋', 'streak', 60);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Immer auf Kurs', 'Haltet eine Antwort-Serie (Streak) von 65 Tagen.', '🧭', 'streak', 65);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Gipfelstürmer', 'Haltet eine Antwort-Serie (Streak) von 70 Tagen.', '🏔️', 'streak', 70);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Neuland-Entdecker', 'Haltet eine Antwort-Serie (Streak) von 75 Tagen.', '🗺️', 'streak', 75);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Meisterklasse', 'Haltet eine Antwort-Serie (Streak) von 80 Tagen.', '🏟️', 'streak', 80);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Ewiger Quell', 'Haltet eine Antwort-Serie (Streak) von 85 Tagen.', '⛲', 'streak', 85);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Vierteljahr-Feuer', 'Haltet eine Antwort-Serie (Streak) von 90 Tagen (3 Monaten).', '🌅', 'streak', 90);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Die dreistellige Hundert', 'Haltet eine Antwort-Serie (Streak) von 100 Tagen.', '💯', 'streak', 100);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Umlaufbahn', 'Haltet eine Antwort-Serie (Streak) von 110 Tagen.', '🪐', 'streak', 110);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Unaufhaltsamer Zug', 'Haltet eine Antwort-Serie (Streak) von 120 Tagen.', '🚂', 'streak', 120);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Außerirdisch gut', 'Haltet eine Antwort-Serie (Streak) von 130 Tagen.', '🛸', 'streak', 130);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Löwenmut', 'Haltet eine Antwort-Serie (Streak) von 140 Tagen.', '🦁', 'streak', 140);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Pokalsieger', 'Haltet eine Antwort-Serie (Streak) von 150 Tagen.', '🏆', 'streak', 150);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Königliche Disziplin', 'Haltet eine Antwort-Serie (Streak) von 180 Tagen (Halbes Jahr!).', '👑', 'streak', 180);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Super-Paar', 'Haltet eine Antwort-Serie (Streak) von 200 Tagen.', '🦸', 'streak', 200);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Sternschnuppen-Regen', 'Haltet eine Antwort-Serie (Streak) von 220 Tagen.', '🌠', 'streak', 220);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Unbezwingbar', 'Haltet eine Antwort-Serie (Streak) von 250 Tagen.', '🦁', 'streak', 250);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Magier der Beständigkeit', 'Haltet eine Antwort-Serie (Streak) von 300 Tagen.', '🧙', 'streak', 300);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Ein Jahr Dauerfeuer!', 'Ihr habt ein ganzes Jahr lang (365 Tage) jeden Tag geantwortet!', '🎇', 'streak', 365);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Erster Eintrag', 'Beantwortet eure erste Frage in Bisou.', '📝', 'answers_count', 1);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Aller guten Dinge...', 'Beantwortet insgesamt 3 Fragen.', '✍️', 'answers_count', 3);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Kleine Bibliothek', 'Beantwortet insgesamt 5 Fragen.', '📚', 'answers_count', 5);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Schreibwütig', 'Beantwortet insgesamt 10 Fragen.', '🖊️', 'answers_count', 10);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Auf Entdeckungsreise', 'Beantwortet insgesamt 15 Fragen.', '🎒', 'answers_count', 15);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Liebes-Landkarte', 'Beantwortet insgesamt 20 Fragen.', '🗺️', 'answers_count', 20);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Neue Türen', 'Beantwortet insgesamt 25 Fragen.', '🚪', 'answers_count', 25);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Schlüsselmomente', 'Beantwortet insgesamt 30 Fragen.', '🔑', 'answers_count', 30);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Bunte Palette', 'Beantwortet insgesamt 35 Fragen.', '🎨', 'answers_count', 35);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Passende Stücke', 'Beantwortet insgesamt 40 Fragen.', '🧩', 'answers_count', 40);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Detailverliebt', 'Beantwortet insgesamt 45 Fragen.', '🔍', 'answers_count', 45);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Das halbe Hundert', 'Beantwortet insgesamt 50 Fragen.', '📖', 'answers_count', 50);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Liebesbriefe', 'Beantwortet insgesamt 60 Fragen.', '💌', 'answers_count', 60);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Teestunde der Gedanken', 'Beantwortet insgesamt 70 Fragen.', '🍵', 'answers_count', 70);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Sommerwiese', 'Beantwortet insgesamt 80 Fragen.', '🌻', 'answers_count', 80);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Lebenskompass', 'Beantwortet insgesamt 90 Fragen.', '🧭', 'answers_count', 90);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Tief verwurzelt', 'Beantwortet insgesamt 100 Fragen.', '🌳', 'answers_count', 100);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Eigener Film', 'Beantwortet insgesamt 120 Fragen.', '🎬', 'answers_count', 120);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Gedankenpalast', 'Beantwortet insgesamt 140 Fragen.', '🏰', 'answers_count', 140);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Kosmische Dimensionen', 'Beantwortet insgesamt 160 Fragen.', '🚀', 'answers_count', 160);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Großes Reisegepäck', 'Beantwortet insgesamt 180 Fragen.', '🎒', 'answers_count', 180);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Gigantischer Speicher', 'Beantwortet insgesamt 200 Fragen.', '💾', 'answers_count', 200);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Bunter Papagei', 'Beantwortet insgesamt 230 Fragen.', '🦜', 'answers_count', 230);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Harmonische Akkorde', 'Beantwortet insgesamt 260 Fragen.', '🎹', 'answers_count', 260);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Doktor der Beziehungsfragen', 'Beantwortet insgesamt 300 Fragen.', '🎓', 'answers_count', 300);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Magisches Zirkuszelt', 'Beantwortet insgesamt 340 Fragen.', '🎪', 'answers_count', 340);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Stadionsprecher', 'Beantwortet insgesamt 380 Fragen.', '🏟️', 'answers_count', 380);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Planetenforscher', 'Beantwortet insgesamt 420 Fragen.', '🪐', 'answers_count', 420);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Feuer und Flamme', 'Beantwortet insgesamt 460 Fragen.', '🌋', 'answers_count', 460);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Diamantene Enzyklopädie', 'Beantwortet insgesamt 500 Fragen.', '💎', 'answers_count', 500);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Krone der Kommunikation', 'Beantwortet insgesamt 550 Fragen.', '👑', 'answers_count', 550);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Imperium der Gefühle', 'Beantwortet insgesamt 600 Fragen.', '🏰', 'answers_count', 600);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Unendliche Weiten', 'Beantwortet insgesamt 650 Fragen.', '🌌', 'answers_count', 650);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Historische Chronik', 'Beantwortet insgesamt 700 Fragen.', '📜', 'answers_count', 700);
INSERT INTO public.milestones (name, description, icon, trigger_type, trigger_value) VALUES ('Legendenstatus', 'Beantwortet insgesamt 730 Fragen (2 Jahre täglich!).', '🎖️', 'answers_count', 730);

-- Recalculate milestones for all existing profiles
DO $$
DECLARE
    p RECORD;
BEGIN
    FOR p IN SELECT id FROM public.profiles LOOP
        PERFORM public.check_and_unlock_milestones(p.id);
    END LOOP;
END $$;